### ISSUE TITLE
Unable to install package using npm 

### ISSUE THREAD

**Issue by rajaningle** [allenhwkim/angular-template#18]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ringle\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular-template" "--save"
npm ERR! node v6.1.0
npm ERR! npm  v3.10.7
npm ERR! code E404

npm ERR! 404 no such package available : @types/node
npm ERR! 404
npm ERR! 404  '@types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parse5'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspace\reporting-service\npm-debug.log

**Comment by FDIM** [comment]
Hi - It appears that there is something wrong with your npm configuration. `'' is not in the npm registry. `

**Comment by rajaningle** [comment]
Hi Sorry if I am missing something here but other packages are getting installed just fine and also previously I have installed it in the different folder without errors.
please check the latest log some problem with @types/node

npm ERR! code E404
npm ERR! 404 Not Found: @types/node@^6.0.46

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ringle\AppData\Roaming\npm-cache\_logs\2017-10-13T11_53_24_717Z-debug.log

Please help me out here.
