### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup ported outside strict mode

### ISSUE THREAD

**Issue by lokinderchauhan** [allenhwkim/angular-template#4]
I am generating documentation with `angular-jsdoc` with gulp. I am successfully able to generate docs with default template but following issue comes with  `angular-template` 

```
processing template: E:\lokinder\tmd\desktop\node_modules\angular-jsdoc\angular-
template\html\layout.html
error in line undefined
E:\lokinder\tmd\desktop\node_modules\angular-template\index.js:140
        throw e;
        ^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup
ported outside strict mode
    at Function (native)
    at templateFunc (E:\lokinder\tmd\desktop\node_modules\js-template\index.js:5
6:12)
    at jsTemplate (E:\lokinder\tmd\desktop\node_modules\js-template\index.js:65:
18)
    at angularTemplate (E:\lokinder\tmd\desktop\node_modules\angular-template\in
dex.js:128:14)
```

**Comment by allenhwkim** [comment]
please use 'use strict' on the first line of your code.

**Comment by ticktockreed** [comment]
Hi, I am also experiencing the same issue (see this ticket: https://github.com/allenhwkim/angular-jsdoc/issues/86). 

All of my files contain 'use strict' at the top, and compilation worked before a recent update. I have reduced my code to one file as below. Any ideas?

```
'use strict';
angular.module('rmOBA.printManifest', ['ngRoute'])

.config(['$routeProvider', function($routeProvider) {
    $routeProvider.when('/print_manifest', {
        templateUrl: 'views/print_manifest/print_manifest.html'
    });
}])
/**
* @memberof rmOBA
* @ngdoc controller
* @name PrintManifest
* @param $scope {service} controller scope
* @param rmResources {service} Google NavigatorGeolocation wrapper
* @description 
*   The View Control for the third and final screen of the app
*/
.controller('PrintManifestCtrl',  [
    '$scope', function(
        $scope
    ) {
       console.log('PrintManifestCtrl');
}])
```

**Comment by GaelBi** [comment]
+1 Hi, I meet the same error...

**Comment by ronaldsnyder** [comment]
I am also having the same issue.

**Comment by RhonanMS** [comment]
The same issue also occurs in my project. All sources have strict mode enabled via 'use strict';

EDIT: I just tried and went back to angular-template@2.0.3 - there the error message is not displayed.

**Comment by allenhwkim** [comment]
@FDIM, can you take a look at this issue? [Difference between 2.0.3 and 2.0.9.](https://github.com/allenhwkim/angular-template/commit/4fdcae0fe3cb98fe446ccbfeab80d58993c7a7a0). I briefly took a look at it and I could not find any bad code.

**Comment by w11** [comment]
+1 Same error for me. 
Solved also by going back to angular-template@2.0.3

**Comment by FDIM** [comment]
Looking into, but I can't really understand why something like that would happen. Will update soon.

**Comment by FDIM** [comment]
See this PR: https://github.com/allenhwkim/angular-jsdoc/pull/89
