### ISSUE TITLE
Make it possible to pass options to cheerio.load

### ISSUE THREAD

**Issue by idmedia-kaiser** [allenhwkim/angular-template#7]
Hi,

currently it is not possible to pass options to cheerio.load.

E.g. if you need { xmlMode: true }

See options
https://github.com/fb55/htmlparser2/wiki/Parser-options

Would it be possible to have something like

```
options :  { 
 cheerioOptions: {
  xmlMode: true
 } 
}

var $ = cheerio.load(html,options.cheerioOptions);
```

**Comment by allenhwkim** [comment]
@FDIM can you take a look into this?

**Comment by FDIM** [comment]
@idmedia-kaiser Done :)
