### ISSUE TITLE
ng-if not working

### ISSUE THREAD

**Issue by sagarb3** [allenhwkim/angular-template#9]
ng-if is not working

**Comment by FDIM** [comment]
Hi there, could it be that you didn't specify ng prefix? default one is ht

**Comment by sagarb3** [comment]
I have prefixed it and it is still not working

**Comment by sagarb3** [comment]
I ended up using jangular in place of this

**Comment by FDIM** [comment]
Alright, I doubt your issue had anything to do with this library though
